### ISSUE TITLE
Roadmap to go to the v1

### ISSUE THREAD

**Issue by Nexucis** [prometheus-community/codemirror-promql#5]
The goal of this issue is to list the different feature we would like to implement in order to provide a nice v1.
The different issues are normally listed by priority

In order to achieve that, we are going to move directly to [CodeMirror 6](https://github.com/codemirror/codemirror.next) which provides much more interesting feature than the previous version such as:
* a grammar syntax called **[lezer](https://lezer.codemirror.net/)**
* everything is a module (or an extension as it is the internal term) which makes CodeMirror much more flexible
* CodeMirror in typescript 

## Replace Monaco
**Goal**:  be able to provide same feature than provided by [monaco-promql](https://github.com/prometheus-community/monaco-promql)

- [x] Provide the npm package **lezer-promql** that will provide the PromQL grammar in the lezer syntax. On @juliusv side
- [x] Create a language extension that takes the package **lezer-promql** in order to have a proper syntax highlightning
- [x] Create an auto-completion extension in order to suggest all PromQL keyword
- [x] In the meantime try to fix the issue https://github.com/codemirror/codemirror.next/issues/236 in order to have an accurate autocomplete list
- [x] In the meantime try to fix the issue https://github.com/codemirror/codemirror.next/issues/234

## Documentations

- [x] Document how to integrate _codemirror-mode_ with Angular
- [ ] Document how to ingegrate _codemirror-mode_ with ReactJS

## Improvement
**Goal**: improve the different feature provided in the previous section while still staying offline
- [x] Provides a way to highlight some syntax error (if not already provided) ==> use the linter. 
   - [x] Should wait the v0.10.0 to be able to display the error message: https://github.com/codemirror/codemirror.next/issues/261
   - [x] Issue https://github.com/codemirror/codemirror.next/issues/270 must be resolved to be able to iterate properly through the tree.
- [x] Improve the auto-completion list with PromQL snippets
- [x] Propose different theme to be used to replace the current one.
- [x] Hybrid Autocompletion should be deeply reviewed to be more flexible / testable / precise

## Test
- [x] Implement unit test to cover and improve potentially the autocompletion

## LSP
**Goal**: Integrate some feature coming from LSP (Language Server Protocol)

- [x] Improve the auto-completion list by getting the metric/labelName /labelValue when it's accurate. Or by using the endpoint **/completion** on Prometheus side, or by using the standard endpoint in prometheus. on @Nexucis side
- [x] Find a way to display the PromQL documentation using the endpoint **/hover** on Prometheus side. ===> Should use the tooltips. Feature is blocked until https://github.com/codemirror/codemirror.next/issues/226 is resolved.
- [x] Use the endpoint **/diagnostics** for the linter

## The craziness
**Goal**: everything that sounds cool and crazy

- [ ] ~~be compatible with CodeMirror 5.~~
- [ ] propose to Prometheus to use codemirror-mode.
- [ ] propose to Thanos to use codemirror-mode.
- [ ] propose to Grafana to use codemirror-mode.

Note: this page will be edited with new feature in case it appears to be important.

**Comment by slrtbtfs** [comment]
Wow, this seems like a quite ambitious Roadmap. Would be great to see that happen!

What's not entirely clear to me is the offline mode. What would be the use case of this?

Especially getting error messages right seems quite hard, since PromQL has an incredible amount of edge cases.

**Comment by Nexucis** [comment]
> What's not entirely clear to me is the offline mode. What would be the use case of this?

Being able to use in a web site that doesn't have access to a prometheus server + potentially reduce the number of http request send to the server when the completion would only return the PromQL syntax.

**Comment by Nexucis** [comment]
> Especially getting error messages right seems quite hard, since PromQL has an incredible amount of edge cases.

Yeah that's true. But let's see how far we can go.

**Comment by slrtbtfs** [comment]
I'm obviously biased here, but my preferred approach would be to integrate the language server first, then add potentially missing features to the language server and then maybe have a look at doing optimisations that aim to reduce the number of LSP requests.

**Comment by dvkndn** [comment]
>  Document how to ingegrate codemirror-mode with ReactJS

Did anyone already working on this? If not I'm happy to work on this :D

**Comment by Nexucis** [comment]
So far there is no specific person I known that is working on that.
Since it is or will be integrated in PromLens by @juliusv and then later in Prometheus, documentation relative to reactJS will come at this moment.

But if you want to work on this, then np :) @dvkndn.
Just keep in mind that the review of the PR could take a bit time since I have a limited access to internet for the moment

**Comment by dvkndn** [comment]
I see. Thank you :D

> Since it is or will be integrated in PromLens by @juliusv and then later in Prometheus, documentation relative to reactJS will come at this moment.

@juliusv do you think that will come soon?

**Comment by juliusv** [comment]
@dvkndn Yeah, I mean I've got it integrated into PromLens (promlens.com) already, just need to find the time to extract and open-source those bits. But I mean, I'm basically just getting a `ref` to a `div` and then doing an initial `useEffect()` to mount the editor in there as usual. Like this:

```typescript
  const containerRef = useRef<HTMLDivElement>(null);
  const viewRef = useRef<EditorView | null>(null);

  // [...stuff...]

  useEffect(() => {
    if (!containerRef.current) {
      throw new Error('expected CodeMirror container element to exist');
    }

    // [...themeing and other stuff...]

    const startState = EditorState.create(/* ... */);

    const view = new EditorView({
      state: startState,
      parent: containerRef.current,
    });

    viewRef.current = view;

    return () => {
      view.destroy();
    };
  }, []);

  return <div ref={containerRef} className="cm-expression-input"></div>
```

**Comment by dvkndn** [comment]
I think that'd be pretty good already, but that's about CodeMirror. I think the part we need to show is how to use the codemirror-promql extension with CodeMirror, like:
- Initialize the extension (just new)
- Choosing a setup (promqlextension.setComplete and setLinter)
- Add the extension to CodeMirror
- Some gotchas, like you need to re-initialize CodeMirror when Linter changes

Also thank you for the snippet above, I didn't know about the destroy/cleanup part :D 

Also do you think we should extract this to an issue on its own? I'm just afraid I'm polluting this important umbrella issue

**Comment by juliusv** [comment]
@dvkndn Ah yeah, so exactly the stuff I omitted in my snippet above, but have in PromLens. But you asked about ReactJS integration, so I only mentioned the parts relevant to that ;) But yeah, I'll aim to extract and OSS that other part soon, it's a bunch of little themeing and other details.

**Comment by dvkndn** [comment]
Thank you!

**Comment by Nexucis** [comment]
Excepting a big changes, I think we are quite close to finish this roadmap.
So focus should be on documentation ( How to use it / functionality ...etc. ) and stability of the code. So far, I don't see other feature to implement.

**Comment by Nexucis** [comment]
I think we can close this PR. The only thing remains now is to put it in Prometheus which will happen one day or another. We already went much further than what we expect at the beginning.

**Comment by juliusv** [comment]
:tada: :rocket:
